# k8s/disponibilidade-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: disponibilidade
  namespace: hotelaria
spec:
  selector:
    app: disponibilidade
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
