apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: hotelaria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: luizdevops/eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
