apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: hotelaria
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 32000
  type: NodePort

