apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: hotelaria
spec:
  selector:
    app: gateway
  ports:
    - port: 9098
      targetPort: 9098
      nodePort: 30080
  type: NodePort
