apiVersion: v1
kind: PersistentVolume
metadata:
  name: h2-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/h2-database"
    type: DirectoryOrCreate