apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-db-pvc
  namespace: hotelaria
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi