apiVersion: v1
kind: Service
metadata:
  name: reserva
  namespace: hotelaria
spec:
  selector:
    app: reserva
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
